// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CentralMsgClient is an autogenerated mock type for the CentralMsgClient type
type CentralMsgClient struct {
	mock.Mock
}

// Unsubscribe provides a mock function with given fields: topic
func (_m *CentralMsgClient) Unsubscribe(topic string) error {
	ret := _m.Called(topic)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(topic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCentralMsgClient creates a new instance of CentralMsgClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCentralMsgClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CentralMsgClient {
	mock := &CentralMsgClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
